# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-test-cm
data:
  # key: value
  # file: |
  #   content
  # ---
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       80;
        server_name  _;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
        location /test {
          return 401;
        }
      }
    }


---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: nginx
        ports:
        - name: web
          containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
  labels:
    app: nginx-test
spec:
  selector:
    app: nginx-test
  type: ClusterIP
  ports:
  - name: http
    port: 80

---
# SSL Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-cert
  namespace: nginx-test
spec:
  secretName: nginx-test-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - nginx.dev01.internal.minipig.org

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
spec:
  rules:
  - host: nginx.dev01.internal.minipig.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-test-svc
            port:
              number: 80
  tls:
  - hosts:
    - nginx.dev01.internal.minipig.org
    secretName: nginx-test-cert