authentik:
    secret_key: "<secret_key>"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "<password>"
    redis:
      host: "redis-master.redis.svc.cluster.local"
      # password: "your-redis-password"

server:
    ingress:
        enabled: false

postgresql:
    enabled: true
    auth:
        password: "<password>"
redis:
    enabled: false