# SSL Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  secretName: harbor-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - registry.dev01.internal.minipig.org


---
# Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingress
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`registry.minipig.org`) && (PathPrefix(`/api/`) || PathPrefix(`/service/`) || PathPrefix(`/v2/`) || PathPrefix(`/chartrepo/`) || PathPrefix(`/c/`))
    kind: Rule
    services:
    - name: harbor-core
      namespace: harbor
      port: 80
  - match: Host(`registry.minipig.org`)
    kind: Rule
    services:
    - name: harbor-portal
      namespace: harbor
      port: 80
  
  tls:
    secretName: harbor-cert
    