externalURL: https://registry.dev01.internal.minipig.org # Leave it as http, even if you are using https
adminPassword: Harbor12345 # Change this password when you login to the Harbor UI
exposureType: ingress

ingress:
  core:
    hostname: registry.dev01.internal.minipig.org
    extraTls:
      - hosts:
        - harbor-cert
        secretName: harbor-cert

redis:
  enabled: false

externalRedis:
  host: "redis-master.redis.svc.cluster.local"
  port: 6379
  password: ZISDjhMpzj