---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-cm
data:
  ddclient.conf: |
    daemon=300
    syslog=yes
    verbose=yes
    pid=/var/run/ddclient.pid
    ssl=yes
    use=web, web=https://icanhazip.com, web-skip='\\n\\n'
    protocol=cloudflare
    login=##_CLOUDFLARE_EMAIL_##
    password=##_CLOUDFLARE_API_KEY_##
    zone=##_ZONE_##
    ##_DOMAINS_##

---
# Startup Script
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-startup
data:
  startup.sh: |
    #!/bin/sh
    echo "Assembling configuration files..."
    cp /tmp/ddclient-cm/ddclient.conf /config/ddclient.conf
    echo "Replacing placeholders..."
    sed -i "s/##_CLOUDFLARE_EMAIL_##/$CLOUDFLARE_EMAIL/g" /config/ddclient.conf
    sed -i "s/##_CLOUDFLARE_API_KEY_##/$CLOUDFLARE_API_KEY/g" /config/ddclient.conf
    sed -i "s/##_ZONE_##/$ZONE/g" /config/ddclient.conf
    sed -i "s/##_DOMAINS_##/$DOMAINS/g" /config/ddclient.conf
    echo "Done!"
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient
spec:
  selector:
    matchLabels: 
      app: ddclient
  replicas: 1
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      initContainers:
      - name: init-ddclient
        image: busybox
        command: ['sh', '-c', '/tmp/ddclient-startup/startup.sh']
        volumeMounts:
        - name: ddclient-startup
          mountPath: /tmp/ddclient-startup
        - name: ddclient-config
          mountPath: /config
        - name: ddclient-cm
          mountPath: /tmp/ddclient-cm
        envFrom:
        - secretRef:
            name: ddclient-secret

      containers:
      - name: ddclient
        image: linuxserver/ddclient
        volumeMounts:
        - name: ddclient-config
          mountPath: /config      
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      volumes:
      - name: ddclient-config
        emptyDir: {}
      - name: ddclient-startup
        configMap:
          name: ddclient-startup
          defaultMode: 0777
      - name: ddclient-cm
        configMap:
          name: ddclient-cm
